# Generated by Django 3.1.4 on 2021-09-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210304_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role_id',
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'manager'), (3, 'normal_member'), (4, 'vip_member')]),
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='USER_ROLE',
        ),
    ]
