
stages :
  - build
  - deploy 


.job_deploy_template :
  stage : deploy
  image : 
    name : amazon/aws-cli
    entrypoint : [""]
  before_script :
    - aws configure set region $AWS_DEFAULT_REGION
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  script :
    - >-
      aws ecs 
  only:
    - other
  tags :
    - ann