
stages :
  - build
  - deploy 

variables :
  CLUSTER : "tutorial"
  PROJECT_NAME : "tutorial"
  CLUSTER_CONFIG : "tutorial"
  ECS_PROFILE : "tutorial-profile"
  AWS_DEFAULT_REGION : "ap-northeast-1"
  AWS_ACCESS_KEY_ID : "AKIAXSGGC3XSBLLMV4JY"
  AWS_SECRET_ACCESS_KEY : "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"

job_build_template :
  stage : build
  image : docker:19.03
  script :
    - docker login --username "lyoudr" --password "Awdxa48624"
    - docker build -f Dockerfile.nginx -t nginx:latest .
    - docker tag nginx:latest lyoudr/nginx_public:latest
    - docker push lyoudr/nginx_public:latest

    - docker build -f Dockerfile.server -t music_server:latest .
    - docker tag music_server:latest lyoudr/music_public:music_1 
    - docker push lyoudr/music_public:music_1
    - docker logout $DOCKER_HUB_PASSWD


job_deploy_template :
  stage : deploy
  image : 
    name : amazon/aws-cli
    entrypoint : [""]
  before_script :
    - aws configure set region $AWS_DEFAULT_REGION
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  script :
    - >-
      ecs-cli compose --project-name $PROJECT_NAME service up --create-log-groups 
      --cluster-config $CLUSTER_CONFIG --ecs-profile $ECS_PROFILE --force-deployment
    - aws ecs wait services-stable --services $CLUSTER --cluster $CLUSTER

build :
  extends : .job_build_template
  stage : build
  only :
    - ecs_fargate
  tags :
    - ann

deploy :
  extends : .job_deploy_template
  stage : deploy
  only : 
    - ecs_fargate
  tags : 
    - ann