version : '3'

services :
  # 1. database
  postgres_db :
    image : postgres:12.5
    environment: 
      - POSTGRES_DB=music
      - POSTGRES_USER=ann
      - POSTGRES_PASSWORD=GxXynskDj134yi7P
    volumes:
      - ./postgres_data:/var/lib/postgresql

    ## can't use healthcheck when running on ECS
    # healthcheck:
    #   test : ["CMD", "pg_isready", "--dbname", "music", "--host", "postgres_db", "-U", "ann"]
    #   timeout: 5sd
    #   retries : 5

  # 2. server 
  # server_1
  ann_server_1:
    ## (ecs) use "image" when running on ECS
    image : lyoudr/music_public:music_1

    ## (local) use "build" when needs to build locally
    
    # build :
    #   context : .
    #   dockerfile: ./docker/config/Dockerfile

    ## (ecs) use "logging" to log error of this container on ECS
    logging :
      driver : awslogs
      options : 
        awslogs-group : music
        awslogs-region : ap-northeast-1
        awslogs-stream-prefix : ann_server_1
  
    environment:
      # system
      - ENV=prod 
      - STATIC_ROOT=/music/static/
      # database
      - DB_HOST=postgres_db
      - DB_NAME=music
      - DB_USER=ann
      - DB_PASSWORD=GxXynskDj134yi7P
      # aws_s3
      - AWS_ACCESS_KEY_ID=AKIAXSGGC3XSBLLMV4JY
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_STORAGE_BUCKET_NAME=lyoudrmusic
    
    ## link ann_server_1 with postgres_db (have to use links in ecs rather than "depends_on")
    links:
      - postgres_db

    restart : always
    volumes : 
      - static-content:/music/static
      - media-content:/tmp/media

  # 3. web server
  nginx :
    ## (ecs) use "image" when running on ECS
    image : lyoudr/nginx_public:latest

    ## (local) use "build" when needs to build locally

    # build :
    #   context : .
    #   dockerfile : ./docker/nginx/Dockerfile
    
    ## (ecs) use "logging" to log error of this container on ECS
    logging :
      driver : awslogs
      options : 
        awslogs-group : music
        awslogs-region : ap-northeast-1
        awslogs-stream-prefix : nginx
    volumes:
      - static-content:/tmp/static
      - media-content:/tmp/media

    ## link nginx with ann_server_1 (have to use links in ecs rather than "depends_on")
    links :
      - ann_server_1 
    ports: 
      - 80:80
      - 443:443

volumes:
  media-content : 
  static-content :


  