version : '3'

services :
  postgres_db :
    image : postgres:12.5
    container_name: postgres_db
    environment: 
      - POSTGRES_DB=music
      - POSTGRES_USER=ann
      - POSTGRES_PASSWORD=GxXynskDj134yi7P

    healthcheck :
      test : ["CMD-SHELL", "pg_isready --dbname music -U ann"]
      timeout : 30s
      retries : 3

  ann_server_1:
    container_name: ann_server_1
    image : lyoudr/music_public:music_1

    healthcheck :
      test : ["CMD-SHELL", "curl -i GET http://localhost:5000/api/blog/class/"]
      timeout : 60s
      retries : 10

    environment:
      - ENV=prod 
      - STATIC_ROOT=/music/static/
      - DB_HOST=postgres_db
      - DB_NAME=music
      - DB_USER=ann
      - DB_PASSWORD=GxXynskDj134yi7P
      - AWS_ACCESS_KEY_ID=AKIAXSGGC3XSBLLMV4JY
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_STORAGE_BUCKET_NAME=lyoudrmusic
    
    restart : always

  nginx :
    image : lyoudr/nginx_public:latest
    ports: 
      - 80:80
      - 443:443
