# If there are volumes to correspond, have to use EBS
version : '3'

services :
  postgres_db :
    image : postgres:12.5
    environment: 
      - POSTGRES_DB=music
      - POSTGRES_USER=ann
      - POSTGRES_PASSWORD=GxXynskDj134yi7P
      - POSTGRES_HOST_AUTH_METHOD=trust

    healthcheck :
      test : ["CMD-SHELL", "pg_isready --dbname music -U ann"]
      timeout : 30s
      retries : 3

  ann_server_1:

    # build:
    #   context: .
    #   dockerfile: Dockerfile.server

    image : lyoudr/music_public:music_1

    # have to write "healthcheck" 
    healthcheck :
      test : ["CMD-SHELL", "curl -i GET http://localhost:5000/api/blog/class"]
      timeout : 60s
      retries : 10
    
    environment:
      - ENV=local
      - STATIC_ROOT=/music/static/
      - DB_HOST=localhost # have to use "localhost" to refer to host when "ecs_network_mode" is "awsvpc" 
      - DB_NAME=music
      - DB_USER=ann
      - DB_PASSWORD=GxXynskDj134yi7P
      - AWS_ACCESS_KEY_ID=AKIAXSGGC3XSBLLMV4JY
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_STORAGE_BUCKET_NAME=lyoudrmusic
      
    logging:
        driver: awslogs
        options: 
          awslogs-group: tutorial
          awslogs-region: ap-northeast-1
          awslogs-stream-prefix: ann_server_1
    volumes:
      - music:/static-root

  nginx :

    # build:
    #   context: .
    #   dockerfile: Dockerfile.nginx

    image : lyoudr/nginx_public:latest

    healthcheck :
      test : ["CMD-SHELL", "nginx", "-t"]
      timeout : 60s
      retries : 10
    
    ports: 
      - 80:80
      - 443:443

    logging:
      driver: awslogs
      options: 
        awslogs-group: tutorial
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: nginx

volumes:
  music: