version : '3.8'

services :
  # 1. web server
  nginx :
    image : lyoudr/music_web:latest
    volumes:
      - ./docker/nginx/nginx_default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/uwsgi/uwsgi_params:/etc/nginx/uwsgi_params
      - static-content:/tmp/static
      - static-content:/tmp/media
    depends_on:
      - ann_server_1
      - ann_server_2
      - ann_server_3
    ports: 
      - 80:80
      - 443:443

  # 2. database
  postgres_db :
    image : postgres:12.5
    environment: 
      - POSTGRES_DB=music
      - POSTGRES_USER=ann
      - POSTGRES_PASSWORD=GxXynskDj134yi7P
    volumes:
      - ./postgres_data:/var/lib/postgresql

    healthcheck:
      test : ["CMD", "pg_isready", "--dbname", "music", "--host", "postgres_db", "-U", "ann"]
      timeout: 5s
      retries : 5

  # 3. server 
  # server_1
  ann_server_1:
    build :
      context : .
      dockerfile: ./docker/config/Dockerfile
    environment:
      # system
      - ENV=prod 
      - STATIC_ROOT=/music/static/
      # database
      - DB_HOST=postgres_db
      - DB_NAME=music
      - DB_USER=ann
      - DB_PASSWORD=GxXynskDj134yi7P
      # aws_s3
      - AWS_ACCESS_KEY_ID=AKIAXSGGC3XSBLLMV4JY
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_STORAGE_BUCKET_NAME=lyoudrmusic
    depends_on:
      - postgres_db
    restart : always
    volumes : 
      - static-content:/music/static
      - static-content:/tmp/media
  
  # server_2
  ann_server_2 :
    build :
      context : .
      dockerfile: ./docker/config/Dockerfile
    environment:
      # system
      - ENV=prod 
      - STATIC_ROOT=/music/static/
      # database
      - DB_HOST=postgres_db
      - DB_NAME=music
      - DB_USER=ann
      - DB_PASSWORD=GxXynskDj134yi7P
      # aws_s3
      - AWS_ACCESS_KEY_ID=AKIAXSGGC3XSBLLMV4JY
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_STORAGE_BUCKET_NAME=lyoudrmusic
    depends_on:
      - postgres_db
    restart : always
    ports : 
      - 5001:5001
    volumes : 
      - static-content:/music/static
      - static-content:/tmp/media
  
  # server_3
  ann_server_3 :
    build :
      context : .
      dockerfile: ./docker/config/Dockerfile
    environment:
      # system
      - ENV=prod 
      - STATIC_ROOT=/music/static/
      # database
      - DB_HOST=postgres_db
      - DB_NAME=music
      - DB_USER=ann
      - DB_PASSWORD=GxXynskDj134yi7P
      # aws_s3
      - AWS_ACCESS_KEY_ID=AKIAXSGGC3XSBLLMV4JY
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_STORAGE_BUCKET_NAME=lyoudrmusic
    depends_on:
      - postgres_db
    restart : always
    volumes : 
      - static-content:/music/static
      - static-content:/tmp/media

volumes:
  static-content : 


  