# Generated by Django 3.1.4 on 2021-10-05 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0007_auto_20210905_0210'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.CharField(max_length=40)),
                ('product_name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_b', to='blog.blogpost')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_a', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PRODUCT',
            },
        ),
    ]
