# Generated by Django 3.1.4 on 2021-10-05 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_no',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
