# Generated by Django 3.1.4 on 2021-11-12 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211005_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_no', models.CharField(choices=[('PS', 'piano_sheet'), ('BK', 'book'), ('CL', 'clothes')], max_length=2)),
            ],
            options={
                'db_table': 'PRODUCT_TYPE',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_c', to='product.producttype'),
        ),
    ]
