# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sales.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sales.proto',
  package='sales',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bsales.proto\x12\x05sales\"\x0b\n\tProductRe\"l\n\x07Product\x12\x14\n\x0cproduct_type\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x12\n\nproduct_no\x18\x03 \x01(\t\x12\x13\n\x0btotal_sales\x18\x04 \x01(\x05\x12\x0c\n\x04rank\x18\x05 \x01(\x05\"c\n\x08\x46\x65\x65\x64\x42\x61\x63k\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04rank\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x12\x17\n\x0fproduct_type_id\x18\x04 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t2x\n\x0bSalesReport\x12\x33\n\x0bListProduct\x12\x10.sales.ProductRe\x1a\x0e.sales.Product\"\x00\x30\x01\x12\x34\n\x0e\x43reateFeedBack\x12\x0f.sales.FeedBack\x1a\x0f.sales.FeedBack\"\x00\x62\x06proto3'
)




_PRODUCTRE = _descriptor.Descriptor(
  name='ProductRe',
  full_name='sales.ProductRe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=33,
)


_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='sales.Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_type', full_name='sales.Product.product_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='product_name', full_name='sales.Product.product_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='product_no', full_name='sales.Product.product_no', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_sales', full_name='sales.Product.total_sales', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rank', full_name='sales.Product.rank', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=143,
)


_FEEDBACK = _descriptor.Descriptor(
  name='FeedBack',
  full_name='sales.FeedBack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sales.FeedBack.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rank', full_name='sales.FeedBack.rank', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='sales.FeedBack.user_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='product_type_id', full_name='sales.FeedBack.product_type_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='sales.FeedBack.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=244,
)

DESCRIPTOR.message_types_by_name['ProductRe'] = _PRODUCTRE
DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
DESCRIPTOR.message_types_by_name['FeedBack'] = _FEEDBACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProductRe = _reflection.GeneratedProtocolMessageType('ProductRe', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTRE,
  '__module__' : 'sales_pb2'
  # @@protoc_insertion_point(class_scope:sales.ProductRe)
  })
_sym_db.RegisterMessage(ProductRe)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'sales_pb2'
  # @@protoc_insertion_point(class_scope:sales.Product)
  })
_sym_db.RegisterMessage(Product)

FeedBack = _reflection.GeneratedProtocolMessageType('FeedBack', (_message.Message,), {
  'DESCRIPTOR' : _FEEDBACK,
  '__module__' : 'sales_pb2'
  # @@protoc_insertion_point(class_scope:sales.FeedBack)
  })
_sym_db.RegisterMessage(FeedBack)



_SALESREPORT = _descriptor.ServiceDescriptor(
  name='SalesReport',
  full_name='sales.SalesReport',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=246,
  serialized_end=366,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListProduct',
    full_name='sales.SalesReport.ListProduct',
    index=0,
    containing_service=None,
    input_type=_PRODUCTRE,
    output_type=_PRODUCT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateFeedBack',
    full_name='sales.SalesReport.CreateFeedBack',
    index=1,
    containing_service=None,
    input_type=_FEEDBACK,
    output_type=_FEEDBACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SALESREPORT)

DESCRIPTOR.services_by_name['SalesReport'] = _SALESREPORT

# @@protoc_insertion_point(module_scope)
