# Generated by Django 3.1.4 on 2021-01-11 07:49

from django.db import migrations, models
import music.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='photo',
            field=models.FileField(null=True, storage=music.storage.select_storage, upload_to='blog_photos'),
        ),
    ]
