# Generated by Django 3.1.4 on 2021-05-20 08:13

from django.db import migrations, models
import django.db.models.deletion
import music.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210520_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=music.storage.select_storage, upload_to='blog_photos')),
            ],
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_section', to='blog.blogphoto'),
        ),
    ]
