# Generated by Django 3.1.4 on 2021-09-05 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210520_0813'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogclass',
            table='BLOG_CLASS',
        ),
        migrations.AlterModelTable(
            name='blogphoto',
            table='BLOG_PHOTO',
        ),
        migrations.AlterModelTable(
            name='blogpost',
            table='BLOG_POST',
        ),
        migrations.AlterModelTable(
            name='blogsection',
            table='BLOG_SECTION',
        ),
    ]
