# Generated by Django 3.1.4 on 2021-10-05 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('01', '購物車'), ('02', '訂單'), ('03', '待出貨'), ('04', '已出貨'), ('05', '已送達')], max_length=2)),
                ('ship_addr', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ORDER',
            },
        ),
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_no', models.CharField(max_length=50)),
                ('card_no', models.CharField(max_length=50)),
                ('card_type', models.CharField(choices=[('1', 'VISA'), ('2', 'MASTER'), ('3', 'CREDIT')], max_length=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PAY_INFO',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_info_a', to='order.order')),
            ],
            options={
                'db_table': 'ORDER_INFO',
            },
        ),
    ]
