# Generated by Django 3.1.4 on 2021-10-05 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_info_b', to='product.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.payinfo'),
        ),
        migrations.AddField(
            model_name='order',
            name='sell_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_a', to=settings.AUTH_USER_MODEL),
        ),
    ]
