# Generated by Django 3.1.4 on 2021-11-12 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211112_0251'),
        ('order', '0004_auto_20211112_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.producttype'),
        ),
    ]
