# Generated by Django 3.1.4 on 2021-11-12 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211112_0257'),
        ('order', '0005_order_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.producttype'),
            preserve_default=False,
        ),
    ]
