# Generated by Django 3.1.4 on 2021-11-25 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20211112_0342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payinfo',
            old_name='bank_name',
            new_name='bank',
        ),
        migrations.RemoveField(
            model_name='payinfo',
            name='bank_no',
        ),
    ]
