# Generated by Django 3.1.4 on 2021-11-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20211125_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinfo',
            name='bank',
            field=models.CharField(choices=[('004', '台灣銀行'), ('005', '台灣土地銀行'), ('006', '合作金庫銀行'), ('007', '第一商業銀行'), ('008', '華南商業銀行'), ('009', '彰化商業銀行'), ('010', '花旗銀行')], max_length=50),
        ),
    ]
